# Generated by Django 4.2 on 2023-07-04 06:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0002_remove_newtodolist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtodolist',
            name='workitemtype',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witype', to='app_todolist.newtodolist'),
        ),
    ]
