# Generated by Django 4.2 on 2023-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0004_newtodolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtodolist',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
