# Generated by Django 4.2 on 2023-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0006_mappingtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingtable',
            old_name='source',
            new_name='parent',
        ),
    ]
