# Generated by Django 4.2 on 2023-07-05 04:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0007_rename_source_mappingtable_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtable',
            name='destination',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest1', to='app_todolist.newtodolist'),
        ),
        migrations.AlterField(
            model_name='mappingtable',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to='app_todolist.newtodolist'),
        ),
    ]
