# Generated by Django 4.2 on 2023-07-10 05:12

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0009_typelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtodolist',
            name='workitemtype',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witype', to='app_todolist.typelist'),
        ),
    ]
